export const APP_TOGGLE_MENU = 'APP_TOGGLE_MENU';
export const APP_TOGGLE_VR = 'APP_TOGGLE_VR';
export const APP_SHOW_CHAT = 'APP_SHOW_CHAT'
export const APP_HIDE_CHAT = 'APP_HIDE_CHAT'
export const APP_SHOW_LOGIN = 'APP_SHOW_LOGIN'
export const APP_HIDE_LOGIN = 'APP_HIDE_LOGIN'

export const PLATFORM_ADD = 'PLATFORM_ADD';
export const SET_HOME_PLATFORM = 'SET_HOME_PLATFORM';
export const FETCH_PLATFORM = 'FETCH_PLATFORM';
export const RECEIVE_PLATFORMS = 'RECEIVE_PLATFORMS';
export const PLATFORMS_FETCH_FAILED = 'PLATFORMS_FETCH_FAILED';
export const UPDATE_PLATFORM = 'UPDATE_PLATFORM';
export const DELETE_PLATFORM = 'DELETE_PLATFORM';
export const LOAD_PLATFORM_DATA = 'LOAD_PLATFORM_DATA';
export const PLATFORM_HOME_INIT = 'PLATFORM_HOME_INIT';
export const PLATFORM_TEST_INIT = 'PLATFORM_TEST_INIT';

export const STRUCTURE_ADD = 'STRUCTURE_ADD';
export const STRUCTURES_FETCH = 'STRUCTURES_FETCH';
export const STRUCTURES_FETCH_DONE = 'STRUCTURES_FETCH_DONE';
export const STRUCTURES_FETCH_FAIL = 'STRUCTURES_FETCH_FAIL';
export const STRUCTURE_UPDATE = 'STRUCTURE_UPDATE';
export const STRUCTURE_DELETE = 'STRUCTURE_DELETE';

export const ENTITY_ADD = 'ENTITY_ADD';
export const ENTITIES_FETCH = 'ENTITIES_FETCH';
export const ENTITIES_FETCH_DONE = 'ENTITIES_FETCH_DONE';
export const ENTITIES_FETCH_FAILED = 'ENTITIES_FETCH_FAILED';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const DELETE_ENTITY = 'DELETE_ENTITY';
export const SELECT_ENTITY = 'SELECT_ENTITY';

export const COMPONENT_ADD = 'COMPONENT_ADD';
export const APPEND_COMPONENT = 'APPEND_COMPONENT';
export const FETCH_COMPONENT = 'COMPONENTS_FETCH';
export const COMPONENTS_FETCH_DONE = 'COMPONENTS_FETCH_DONE';
export const COMPONENTS_FETCH_FAILED = 'COMPONENTS_FETCH_FAILED';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const TOOL_ADD = 'TOOL_ADD';
export const TOOLS_FETCH = 'TOOLS_FETCH';
export const TOOLS_FETCH_DONE = 'TOOLS_FETCH_DONE';
export const TOOLS_FETCH_FAILED = 'TOOLS_FETCH_FAILED';
export const TOOL_USE = 'TOOL_USE';
export const TOOL_DELETE = 'TOOL_DELETE';
export const TOOL_NEXT = 'TOOL_NEXT';
export const TOOL_PREVIOUS = 'TOOL_PREVIOUS';

export const USER_ADD = 'USER_ADD';
export const USER_CONNECT = 'USER_CONNECT';
export const USER_DISCONNECT = 'USER_DISCONNECT';
export const USERS_FETCH = 'USERS_FETCH';
export const USERS_FETCH_DONE = 'USERS_FETCH_DONE';
export const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ADD_AVATAR = 'ADD_AVATAR';
export const FETCH_AVATAR = 'FETCH_AVATARS';
export const NEXT_AVATAR = 'NEXT_AVATAR';
export const PREVIOUS_AVATAR = 'PREVIOUS_AVATAR';
export const RECEIVE_AVATARS = 'RECEIVE_AVATARS';
export const FAILED_FETCH_AVATARS = 'FAILED_FETCH_AVATARS';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const DELETE_AVATAR = 'DELETE_AVATAR';

export const ADD_NPC = 'ADD_NPC';
export const FETCH_NPC = 'FETCH_NPCS';
export const RECEIVE_NPCS = 'RECEIVE_NPCS';
export const FAILED_FETCH_NPCS = 'FAILED_FETCH_NPCS';
export const UPDATE_NPC = 'UPDATE_NPC';
export const DELETE_NPC = 'DELETE_NPC';

export const ADD_PAGE = 'ADD_PAGE';
export const FETCH_PAGE = 'FETCH_PAGE';
export const PAGES_FETCH_DONE = 'PAGES_FETCH_DONE';
export const PAGES_FETCH_FAIL = 'PAGES_FETCH_FAIL';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const DELETE_PAGE = 'DELETE_PAGE';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const FAILED_FETCH_MESSAGES = 'FAILED_FETCH_MESSAGES';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const ADD_FILE = 'ADD_FILE';
export const FETCH_FILE = 'FETCH_FILES';
export const RECEIVE_FILES = 'RECEIVE_FILES';
export const FAILED_FETCH_FILES = 'FAILED_FETCH_FILES';
export const UPDATE_FILE = 'UPDATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';
